* Init script now follows conventions better  * Created an nntsc.conf that can be installed into /etc/ as default config  * Added code to detect if default config has not been edited and will halt as a result with an error message  * Updated README to match how init script and config will work  * Fixed bug where reporting a database binding error would cause a crash instead  * Try to catch errors when opening a pid file  * Fixed dependency bug where we were installing the wrong daemon library

diff --git a/initscripts/nntsc b/initscripts/nntsc
--- a/initscripts/nntsc
+++ b/initscripts/nntsc
@@ -2,16 +2,9 @@
 
 PATH=/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/local/bin/nntsc
-NAME=NNTSC
-PIDFILE=nntsc.pid
-
-if [ "$#" -lt 2 ] ; then
-  	N=/etc/init.d/$DAEMON
-	echo "Usage: $N <configfile> {start|stop|restart}" >&2
-	exit 1
-fi	
-
-CONF=$1
+NAME=nntsc
+PIDFILE=/tmp/nntsc.pid
+CONF=/etc/nntsc.conf
 
 export PATH=$PATH
 
@@ -20,30 +13,35 @@ test -x $DAEMON || exit 0
 
 set -e
 
-case "$2" in
+case "$1" in
   start)
   	echo "Starting $NAME"
-	start-stop-daemon --start --quiet --exec $DAEMON \
-		-- -P /var/run/$PIDFILE -C $CONF -b
-	echo "Started"
+	start-stop-daemon --quiet --start --exec $DAEMON \
+		-- -P $PIDFILE -C $CONF -b
+	
+	if [ $? -ne 0 ]; then
+		echo "Failed to start $NAME"
+	else
+		echo "Started"
+	fi
 	;;
   stop)
   	echo "Stopping $NAME"
-	start-stop-daemon --stop --quiet --pidfile /var/run/$PIDFILE --oknodo
+	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
 	echo "Stopped"
 	;;
   restart)
   	echo "Restarting $NAME"
-	start-stop-daemon --stop --quiet --pidfile /var/run/$PIDFILE --oknodo
+	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
 	echo "Stopped"
 	sleep 1
 	start-stop-daemon --start --quiet --exec $DAEMON \
-		-- -P /var/run/$PIDFILE -C $CONF -b
+		-- -P $PIDFILE -C $CONF -b
 	echo "Restarted"
 	;;
   *)
-  	N=/etc/init.d/$DAEMON
-	echo "Usage: $N <configfile> {start|stop|restart}" >&2
+  	N=/etc/init.d/$NAME
+	echo "Usage: $N {start|stop|restart}" >&2
 	exit 1
 	;;
 esac
