Bring init script in line with Debian Wheezy standards.

diff --git a/debian/init b/debian/init
--- a/debian/init
+++ b/debian/init
@@ -1,75 +1,132 @@
-#!/bin/sh
+#! /bin/sh
 ### BEGIN INIT INFO
 # Provides:          nntsc
-# Required-Start:    $remote_fs $network $local_fs
-# Required-Stop:     $remote_fs $network $local_fs
+# Required-Start:    $remote_fs $network $syslog
+# Required-Stop:     $remote_fs $network $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: NNTSC data collector
 # Description:       NNTSC data collector
 ### END INIT INFO
 
-PATH=/usr/local/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/bin/nntsc
+# Author: Brad Cowie <brad@wand.net.nz>
+
+# Do NOT "set -e"
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/usr/local/bin:/sbin:/usr/sbin:/bin:/usr/bin
+DESC="NNTSC data collector"
 NAME=nntsc
-USER=""     # Change this in /etc/default/nntsc
-GROUP=""    # Change this in /etc/default/nntsc
-
-# These should get overridden by the contents of /etc/default/nntsc
+DAEMON=/usr/bin/nntsc
+USER=root
+GROUP=root
 CONF=/etc/nntsc/nntsc.conf
-PIDFILE=/tmp/nntsc.pid
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
 
-export PATH=$PATH
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-if test -f /etc/default/nntsc; then
-	. /etc/default/nntsc
-fi
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-test -f $CONF || exit 0
-test -x $DAEMON || exit 0
-
-# quick attempt to make sure people actually look at the config file
+# Quick attempt to make sure people actually look at the config file
 if [ ! "$START_DAEMON" -gt 0 ]; then
     echo 'Not starting nntsc: edit config in /etc/nntsc/nntsc.conf and' >&2
     echo 'enable the daemon in /etc/default/nntsc' >&2
     exit 0
 fi
 
-set -e
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
+# and status_of_proc is working.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+		|| return 1
+	start-stop-daemon --start --quiet --chuid $USER:$GROUP --exec $DAEMON -- \
+		-P $PIDFILE -C $CONF -b \
+		|| return 2
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+	RETVAL="$?"
+	[ "$RETVAL" = 2 ] && return 2
+	return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
+	return 0
+}
 
 case "$1" in
   start)
-  	echo "Starting $NAME"
-	start-stop-daemon --quiet --start --chuid $USER:$GROUP --exec $DAEMON \
-		-- -P $PIDFILE -C $CONF -b
-
-	if [ $? -ne 0 ]; then
-		echo "Failed to start $NAME"
-	else
-		echo "Started"
-	fi
+	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+	do_start
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
 	;;
   stop)
-  	echo "Stopping $NAME"
-	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
-	echo "Stopped"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+	do_stop
+	case "$?" in
+		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
+	;;
+  status)
+	status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
 	;;
   restart|force-reload)
-  	echo "Restarting $NAME"
-	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo
-	echo "Stopped"
-	sleep 1
-	start-stop-daemon --start --quiet --exec $DAEMON \
-		-- -P $PIDFILE -C $CONF -b
-	echo "Restarted"
+	log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
+	case "$?" in
+	  0|1)
+		do_start
+		case "$?" in
+			0) log_end_msg 0 ;;
+			1) log_end_msg 1 ;; # Old process is still running
+			*) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	  *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
   *)
-  	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|restart}" >&2
-	exit 1
+	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	exit 3
 	;;
 esac
 
-exit 0
-
-
+:
